### ISSUE TITLE
Comentarios de pares por Cristian Ulises Barenca Sotelo 💬

### ISSUE THREAD

**Issue by CBarenca** [Jolmed26/PrediccionRotacionPersonal#10]
Estimados JOSE LUIS MEDRANO MEDRANO & HUGO FERNANDO ABARCA JIMENEZ:

Con base en los entregables y puntos a calificar del proyecto final de la materia de Desarrollo de Proyectos l, comparto las siguientes observaciones punto por punto:

# 1. Repositorio en GitHub

__Excelente ⭐__

Se mantiene y se cumple con la estructura del repositorio, actualización del archivo README de la carpeta raíz, la estructura del repositorio es la recomendada, se cumple con los archivos para el análisis final y los resultados del análisis realizado están en la carpeta results.

__Área de mejora 🎯__

Ortografía

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/README.md) | Línea 3

```
En este repositorio se pretende desarrollar un modelo predictivo para la rotación de personal para empresas manufacturereras.
```

**Sugerencia: cambiar la palabra manufacturereras por manufactureras.**

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/README.md) | Línea 11

```
Se ralizó un análisis exploratorio de datos con el objetivo de limpiar el set de datos inicial y detectar variables y relaciones valiosas.
```

**Sugerencia: cambiar la palabra ralizó por realizó.**

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/README.md) | Línea 15

```
Al iniciar el análisis exploratorio de datos, la base de datos tenía 16 variables, 502 entradas y 948 valores nulos, luego del proceso de limpieza de datos se concluyó con 14 variables, 495 registros y 0 valores núlos.
```

**Sugerencia: cambiar la palabra núlos por nulos, como lo tienen anteriormente.**

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/README.md) | Línea 125

```
Del análisis de sentimientos se detectó que la mayoría de párrafos tenían una conotación negativa aunque se cuestiona el resultado pudiera ser discutido ya que los motivos son más bien postulados que no se prestan a un análisis más profundo.
```

**Sugerencia: cambiar la palabra, conotación por connotación.**

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/README.md) | Línea 158 & 171 

```

analisis_sentimientos_Biagram.png     <- Análisis de sentimientos biagrama relaciones.

visual_altair.ipynb   <- Archivo de código con análisis EDA implementando graficos de Altair Gallery

```

**Sugerencia:**

1. Por biagrama, ¿Quisieron decir diagrama?

2. cambiar la palabra graficos por gráficos. 

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/data/README.md) | Línea 3

```
La fuente de datos de este trabajo es **estrucurada** en formato xlsx. Los datos son **privados** y se eliminó toda la información sensible por privacidad de los datos. Esta base de datos contiene información sobre rotación de personal en empresas manufactureras de Tala, Jalisco. 
```

**Sugerencia: cambiar la palabra estrucurada por estructurada.**

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/doc/README.md) | Línea 7

```
1. Determinar de los algoritmoss supervisados k medias, regresión logística, arboles de decisión, random forest, support vector machine y Naive Bayes cuál predice con mayor eficiencia la rotación de personal en empresas manufactureras de Tala, Jalisco. 
```

**Sugerencia:**
1. cambiar la palabra: algoritmoss por algoritmos.
2. cambiar la palabra: arboles por árboles.

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/results/README.md) | Línea 3 & 5

```

Esta carpeta contiene los resultados obtenidos de cada ejercicios.  

__EDA:__ analisis exploratorio, data set limpio resultante del análisis EDA.

```

**Sugerencia:**
1. cambiar la palabra: ejercicios por ejercicio.
2. cambiar la palabra: analisis por análisis.

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/results/analisis_sentimientos/README.md) | Línea 13

```

En el diagrama de correlación de palabras se detectó relaciones interesantes como __problemas familiares, problemas en la inducción, problemas con la residencia y con el desempeño__, esto nos da una idea de que en su mayoría es la percepción de problemas en distintos aspectos lo que genera rotación de personal en la industria manufacturarera, ahora bien, estas relaciones muestran los problemas que hay que atender para aminorar la rotación.


```

**Sugerencia: cambiar la palabra: manufacturarera por manufacturera.**

Archivo [README.md](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/README.md) | Línea 3

```

El Jupyter Notebook de esta carpeta sigue el esquema de análisis EDA. Este análisis es un proceso iterativo, así que se actualizará constantemente a medida que se determinen metodologías más adecuadas para el análisis de este trabajo, se pretende revisar el tratamiento de datos núlos ya que se utilizó un enfoque subjetivo

```
**Sugerencia: cambiar la palabra núlos por nulos.**

Archivo [EDA.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA.ipynb) | Bloque 1

```
La fuente de datos de este trabajo es estrucurada en formato xlsx. Los datos son privados y se eliminó toda la información sensible por privacidad de los datos. Esta base de datos contiene información sobre rotación de personal de empresas manufactureras de Tala, Jalisco.

Se trata de una base de datos transversal que comprende del 20 de abril del 2021 al 30 de abril del 2024.
```

**Sugerencia: cambiar la palabra estrucurada por estructurada.**

Archivo [EDA.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA.ipynb) | Bloque **Descripción de variables**

```

Nota:
Fecha de nacimiento del 2022 es erronea ya que la edad mínima para trabajar es de 18 años, se actualizarán valores menores a 18 con 18.

```

**Sugerencia: cambiar la palabra erronea por errónea.**

Archivo [EDA.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA.ipynb) | Bloque **Descripción de variables**

```

Nota:
Existen valores núlos que no permiten tener certeza de los mínimos y máximos.

```

**Sugerencia: cambiar la palabra núlos por nulos.**

Archivo [EDA.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA.ipynb) | Bloque **Descripción de variables**

```

Nota:
Se tienen qué englobar las siguientes categorías:

VOLUNTARIA: RENUNCIA VOLUNTARIA, SEPARACION VOLUNTARIA, VOLUNTARIA, SEPARACION VOLUNTARIA
ABANDONO: ABANDONO, ABANDONO DE EMPLEO, BAJA POR FALTAS
BAJA: RESCISION DE CONTRATO, BAJA, BAJA POR CIERRE DE BODEGA, RECORTE DE PERSONAL, CAMBIO A TIJUANA, TERMINACION, RECISION DE CONTRATO, BAJA POR DESEMPEÑO, TERMINATION, TERMINO DE CONTRATO, TERMINO DE CONTRATO

Para un total de 7 categorías

```

**Sugerencia: cambiar la palabra qué por que.**

Archivo [EDA.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA.ipynb) | Bloque **Descripción de variables**

```

Nota:
Los salarios tienen múchos valores nulos que sería conveniente llenar con la media.
Quizá vale la pena sólo considerar el salario mensual o el salario diario ya que aportan la misma información
Los valores nulos en baja y días laborados corresponden a personal que aún está activo
Fecha de nacimiento se puede rellenear con la media de edades ya que existen 214 valores núlos

```

**Sugerencia:**
1. cambiar la palabra: múchos por muchos.
2. cambiar la palabra: sólo por solo.
3. cambiar la palabra: rellenear por rellenar.
4. cambiar la palabra: núlos por nulos.

Archivo [EDA.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA.ipynb) | Bloque **4. Valores faltantes**

```

Fecha de baja
Fecha de baja aporta información pero tiene valores nulos, para darle un mayor uso, se renombra como ultimo registro y se actualizan los valores núlos con el último registro del empleado.

```

**Sugerencia:**
1. cambiar la palabra: ultimo  por último.
2. cambiar la palabra: núlos por nulos.

Archivo [EDA.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA.ipynb) | Bloque **4. Valores faltantes**

```

Area
Se filtran los valores en blanco en area y se detecta que todos corresponden a intendencia, valor que se planeaba eliminiar ya que este no tiene relación con este análisis en específico.

```

**Sugerencia:**
1. cambiar la palabra: area  por área.
2. cambiar la palabra: eliminiar por eliminar.

Archivo [EDA_Analisis_sentimientos.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA_Analisis_sentimientos.ipynb) | Bloque **1. Fuentes de datos**

```

1. Fuentes de datos
La fuente de datos de este trabajo es estrucurada en formato xlsx. Los datos son privados y se eliminó toda la información sensible por privacidad de los datos. Esta base de datos contiene información sobre rotación de personal de empresas manufactureras de Tala, Jalisco.

Se trata de una base de datos transversal que comprende del 20 de abril del 2021 al 30 de abril del 2024.

Para este trabajo sólo se extraerá el corpus de texto para realizar un análisis de sentimientos posterior.

```

**Sugerencia:**
1. cambiar la palabra: estrucurada por estructurada.
2. cambiar la palabra: sólo  por solo.

Archivo [EDA_Analisis_sentimientos.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/EDA_Analisis_sentimientos.ipynb) | Bloque **4. Creación de df**

```
4. Creación de df
```

**Sugerencia: Con base en el índice del notebook, cambiar el punto 4. por 5.**

Archivo [visual_altair.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/visual_altair.ipynb) | Bloque **1. Fuentes de datos**

```
1. Fuentes de datos
La fuente de datos de este trabajo es estrucurada en formato xlsx. Los datos son privados y se eliminó toda la información sensible por privacidad de los datos. Esta base de datos contiene información sobre rotación de personal de empresas manufactureras de Tala, Jalisco.

Se trata de una base de datos transversal que comprende del 20 de abril del 2021 al 30 de abril del 2024.
```

**Sugerencia: cambiar la palabra estrucurada por estructurada.**

Archivo [visual_altair.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/visual_altair.ipynb) | Bloque **4. Visualización de datos**

```
4. Visualización de datos
```

**Sugerencia: De acuerdo con el índice, el bloque 4. Visualización de datos pertenece al número 5.**

Archivo [visual_altair.ipynb](https://github.com/Jolmed26/PrediccionRotacionPersonal/blob/main/src/visual_altair.ipynb) | Bloque **2. Referencias**

```
2. Referencias
```

**Sugerencia: De acuerdo con el índice, el bloque 2. Referencias pertenece al número 6.**

# 2. Análisis final considerando 2 de las 6 herramientas revisadas durante la segunda parte del semestre

Se observa que utilizaron Altair & Spacy para el desarrollo de la actividad.

# 3. Participación de ambos compañeros del equipo en el proyecto.

Ambos estudiantes realizaron las diferentes modificaciones al proyecto, JOSE LUIS MEDRANO MEDRANO con 44 commits & HUGO FERNANDO ABARCA JIMENEZ con 15 commits.

# 4. Comentarios de pares a proyecto final

Recomendaciones 🚨

>[!TIP]
**1. Ortografía**

Chicos, favor de revisar las sugerencias que les hago en la parte 1, validen si las sugerencias son válidas, por favor, con ayuda de su validador de gramática de confianza. En Internet existen varios como LanguageTool, Grammarly, entre otros.

>[!TIP]
**2. Buenas prácticas de programación**

En algunos archivos noto que incluyen la librería matplotlib, específicamente en el archivo visual_altair.ipynb, ubicado en la carpeta src, por favor, declaren únicamente las librerías que son necesarias para el desarrollo del proyecto, en este caso no afecta al desarrollo de su trabajo, pero en caso de que alguien quiera retomar el trabajo le va a costar trabajo saber en qué parte del código se hace uso de esa librería, también implica un consumo innecesario de recursos (memoria).

>[!NOTE]
Los estudiantes realizaron un gran esfuerzo por incluir Altair y Spacy en su proyecto final, considero que las observaciones realizas son menores. Felicitaciones a los estudiantes, me gusto mucho su proyecto en especial el graficado con Altair, es notorio que se tomaron su tiempo para realizar el trabajo, excelente trabajo 💯. 

# 5. Difusión del proyecto

El estudiante JOSE LUIS MEDRANO MEDRANO se encargó de dar difusión del proyecto final vía [LinkedIn] (https://www.linkedin.com/posts/jos%C3%A9-luis-medrano-medrano-351822124_cu%C3%A1les-son-los-principales-motivos-de-activity-7267359884730359809-FgAK?utm_source=share&utm_medium=member_desktop).

# 6. Respetar el deadline

Se respetó el deadline, entregando el proyecto el día martes 26 de noviembre del 2024 a los revisores.

**Nota: Para la revisión de la ortografía se utilizó la herramienta disponible en la Web LanguageTool.**

**Comment by Fabarcajim** [comment]
Se corrigen las anotaciones proporcionadas por los compañeros

**Comment by vcuspinera** [comment]
¡Gracias por compartir tus comentarios @CBarenca!
Saludos, Víctor
