### ISSUE TITLE
Aclaración en documentación: Variable 'motivo de renuncia' aparece como eliminada y analizada en la descripción del README.md

### ISSUE THREAD

**Issue by edd885** [Jolmed26/PrediccionRotacionPersonal#8]
En primer lugar, quiero felicitar al autor por el exhaustivo trabajo realizado en este análisis de rotación de personal. El estudio presenta visualizaciones valiosas y hallazgos significativos que pueden ser de gran utilidad para la toma de decisiones en el sector manufacturero de Jalisco.

Durante la revisión del documento, he identificado una inconsistencia que considero importante señalar para mejorar aún más la calidad de esta investigación. En la sección "Análisis exploratorio de datos (EDA)", específicamente en la parte de Resultados, se menciona que la variable "motivo de renuncia" fue eliminada durante el proceso de limpieza de datos, argumentando que "por su cantidad de valores faltantes y tratarse de texto abierto, su análisis va más allá del alcance de este estudio". Sin embargo, en la sección final titulada "Análisis de texto", se presenta un análisis detallado de esta misma variable, incluyendo un estudio de N-grams, análisis de sentimientos y una descripción de los motivos más frecuentes de renuncia, llegando incluso a conclusiones específicas sobre las razones principales por las que los empleados abandonan sus trabajos.

Se sugiere:
1. Aclarar si la variable fue realmente eliminada o si se utilizó para análisis posteriores
2. Si la variable fue analizada, actualizar la sección de EDA para reflejar que el campo se conservó para el análisis de texto
3. Si la variable fue efectivamente eliminada, remover la sección de análisis de texto o explicar si se utilizó otra fuente de datos para este análisis

Esta observación busca fortalecer la coherencia interna del documento y mejorar su valor como referencia para futuros estudios en el campo de la rotación de personal en la industria manufacturera.

**Comment by Jolmed26** [comment]
Me gustaría  agradecer el nivel de detalle y explicación con relación a esta anotación, efectivamente, inicialmente el plan no era incluir un análisis de sentimientos, no obstante, al hacerlo se adecuó la redacción para comunicar que la variable se elimina de este proceso, pero se conserva en un data set independiente para el análisis de texto final, con esto doy por cerrado este issue.

**Comment by vcuspinera** [comment]
¡Gracias por compartir tus comentarios @edd885!
Saludos, Víctor
